config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help", as: "helf"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("name_book"), "http://www.railstutorial.org/" %>
    <%= t "write" %>
    <%= link_to t("author"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("page_about"), about_path %></li>
      <li><%= link_to t("page_contact"), contact_path %></li>
      <li><%= link_to t("page_new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="logo">
      <%= link_to t("app_name"), root_path %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("page_home"), root_path %></li>
        <li><%= link_to t("page_help"), helf_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("all_user"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= t "account" %><b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("setting"), 
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("page_logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("page_login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %> 
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= link_to "English", locale: "en" %>
      <%= link_to "Vietnamese", locale: "vi" %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>